services:
  postgres-db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - backend

  django-app:
    build:
      context: ../backend/main
      dockerfile: Dockerfile
    command: ["./django-web-app-entrypoint.sh"]
    env_file:
      - .env
    volumes:
      - ../backend/main:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    restart: always
    networks:
      - backend

  payment-service:
    build:
      context: ../backend/services/payments
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - postgres-db
    restart: always
    networks:
      - backend

  ml-service:
    build:
      context: ../backend/services/machinelearning
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres-db
    restart: always
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge