services:
  django:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    depends_on:
      - postgres-db
    networks:
      - app_network

  postgres-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ../backend/databases/insurance/Insurance.sql:/docker-entrypoint-initdb.d/Insurance.sql
      - ../backend/databases/ml/Models.sql:/docker-entrypoint-initdb.d/Models.sql
      - ../backend/databases/payments/Transactions.sql:/docker-entrypoint-initdb.d/Transactions.sql
      - ../backend/databases/traffic/Network.sql:/docker-entrypoint-initdb.d/Network.sql
      - ../backend/databases/users/Users.sql:/docker-entrypoint-initdb.d/Users.sql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres-db
    networks:
      - app_network

  payment-service:
    build:
      context: ../backend/services/payments
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - postgres-db
    restart: always
    networks:
      - app_network

  ml-service:
    build:
      context: ../backend/services/machinelearning
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres-db
    restart: always
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
