name: Eslint Testing

on:
  pull_request:
    paths:
      - 'project/frontend/**'

jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project/frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint