name: Eslint

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Project/frontend/**
    steps:
      - name: Install dependencies
        run: |
          cd Project/frontend
          npm ci
      - name: Run eslint
        run: |
          cd Project/frontend/src
          npm run lint
      - name: Build
        run: |
          cd Project/frontend
          npm run build