name: Eslint

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Project/frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
