name: Eslint Testing

on:
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2