name: Eslint Testing

on:
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: stefanoeb/eslint-action@1.0.2
        with:
          node-version: '20'